work around suse9.0 videodev2.h problem

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24452,6 +24452,63 @@ fi
 done
 
 
+if test $v4l2 = yes; then
+echo "$as_me:$LINENO: checking for struct v4l2_buffer in videodev2.h" >&5
+echo $ECHO_N "checking for struct v4l2_buffer in videodev2.h... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <linux/types.h>
+#include <linux/videodev2.h>
+
+int
+main ()
+{
+
+struct v4l2_buffer buf;
+buffer.memory   = V4L2_MEMORY_MMAP
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  v4l2=yes
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_STRUCT_V4L2_BUFFER 1
+_ACEOF
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+v4l2=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 
 
 echo "$as_me:$LINENO: checking for v4l support" >&5
