check CXX flags

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13911,6 +13911,57 @@ echo "${ECHO_T}$ac_cv_try_cflags_ok" >&6
     fi
 
 
+OPT_CXXFLAGS="$CXXFLAGS -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64"
+echo "$as_me:$LINENO: checking if $CXX supports $OPT_CXXFLAGS flags" >&5
+echo $ECHO_N "checking if $CXX supports $OPT_CXXFLAGS flags... $ECHO_C" >&6
+    SAVE_CXXFLAGS="$CXXFLAGS"
+    CXXFLAGS="$OPT_CXXFLAGS"
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_try_cflags_ok=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_try_cflags_ok=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+    CXXFLAGS="$SAVE_CXXFLAGS"
+    echo "$as_me:$LINENO: result: $ac_cv_try_cflags_ok" >&5
+echo "${ECHO_T}$ac_cv_try_cflags_ok" >&6
+    if test x"$ac_cv_try_cflags_ok" = x"yes"; then
+	CXXFLAGS=$OPT_CXXFLAGS
+    else
+	:
+    fi
+
+
 
 statbuf=yes
 echo "$as_me:$LINENO: checking for internal static framebuffer support" >&5
