this patch add a new "meta" module that enable transcode to encode   a video and audio stream on different machine using the PVM3   library (Parallel Virtual Machine) in a distributed processing   environments.
  More details in the docs/export_pvm.txt file.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LN_S CCAS CCASFLAGS ASFLAGS SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE SUPPORTOBJECTS SUPPORTLIB SUPPORTINCL DLDARWINOBJECTS DLDARWINLIB DLDARWININCL DLLDFLAGS BIG_ENDIAN_TRUE BIG_ENDIAN_FALSE LIBOBJS ALLOCA GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS NASM NASMFLAGS HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_3DNOW_TRUE HAVE_ASM_3DNOW_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE ECHO RANLIB ac_ct_RANLIB LIBTOOL LTLIBOBJS STATBUFFER NET_STREAM_TRUE NET_STREAM_FALSE NET_STREAM AVIFILE_CONFIG AVIFILE_CFLAGS AVIFILE_LIBS HAVE_AVIFILE_TRUE HAVE_AVIFILE_FALSE FT2_CONFIG FT2_CFLAGS FT2_LIBS HAVE_FREETYPE2_TRUE HAVE_FREETYPE2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE LAME_3_89 LAME_CFLAGS LAME_LIBS HAVE_LAME_TRUE HAVE_LAME_FALSE LAME_3_89_TRUE LAME_3_89_FALSE OGG_CFLAGS OGG_LIBS HAVE_OGG_TRUE HAVE_OGG_FALSE VORBIS_CFLAGS VORBIS_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE THEORA_CFLAGS THEORA_LIBS HAVE_THEORA_TRUE HAVE_THEORA_FALSE DVDREAD_CFLAGS DVDREAD_LIBS HAVE_LIBDVDREAD_TRUE HAVE_LIBDVDREAD_FALSE XVID_DEFAULT LIBMPEG3_LIBS LIBMPEG3_CFLAGS HAVE_LIBMPEG3_TRUE HAVE_LIBMPEG3_FALSE LIBPOSTPROC_LIBS LIBPOSTPROC_CFLAGS HAVE_LIBPOSTPROC_TRUE HAVE_LIBPOSTPROC_FALSE LIBLVE_LIBS LIBLVE_CFLAGS HAVE_LIBLVE_TRUE HAVE_LIBLVE_FALSE QT_LIBS QT_CFLAGS HAVE_QT_TRUE HAVE_QT_FALSE OPENQT_LIBS OPENQT_CFLAGS HAVE_OPENQT_TRUE HAVE_OPENQT_FALSE DV_LIBS DV_EXTRA_LIBS DV_CFLAGS HAVE_DV_TRUE HAVE_DV_FALSE LZO_LIBS LZO_EXTRA_LIBS LZO_CFLAGS HAVE_LZO_TRUE HAVE_LZO_FALSE A52_LIBS A52_CFLAGS HAVE_A52_TRUE HAVE_A52_FALSE USE_LIBA52_DECODER LIBXML2_CFLAGS LIBXML2_LIBS LIBXML2CONFIG HAVE_LIBXML2_TRUE HAVE_LIBXML2_FALSE MJPEG_CFLAGS MJPEG_LIBS MJPEGTOOLSCONFIG HAVE_MJPEG_TRUE HAVE_MJPEG_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries HAVE_X11_TRUE HAVE_X11_FALSE HAVE_LIBXV_TRUE HAVE_LIBXV_FALSE HAVE_XAW_SIMPLE_TRUE HAVE_XAW_SIMPLE_FALSE HAVE_LIBXPM_TRUE HAVE_LIBXPM_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE HAVE_DIVX_DECORE_TRUE HAVE_DIVX_DECORE_FALSE HAVE_DIVX_ENCORE2_TRUE HAVE_DIVX_ENCORE2_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS HAVE_GTK_TRUE HAVE_GTK_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE MAGICK_CONFIG MAGICK_CFLAGS MAGICK_LIBS HAVE_MAGICK_TRUE HAVE_MAGICK_FALSE LIBJPEG_CFLAGS LIBJPEG_LIBS HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE MOD_PATH HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE HAVE_SSE_TRUE HAVE_SSE_FALSE TRANSCODE_0_6_TRUE TRANSCODE_0_6_FALSE'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LN_S CCAS CCASFLAGS ASFLAGS SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE SUPPORTOBJECTS SUPPORTLIB SUPPORTINCL DLDARWINOBJECTS DLDARWINLIB DLDARWININCL DLLDFLAGS BIG_ENDIAN_TRUE BIG_ENDIAN_FALSE LIBOBJS ALLOCA GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS NASM NASMFLAGS HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_3DNOW_TRUE HAVE_ASM_3DNOW_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE ECHO RANLIB ac_ct_RANLIB LIBTOOL LTLIBOBJS STATBUFFER NET_STREAM_TRUE NET_STREAM_FALSE NET_STREAM AVIFILE_CONFIG AVIFILE_CFLAGS AVIFILE_LIBS HAVE_AVIFILE_TRUE HAVE_AVIFILE_FALSE FT2_CONFIG FT2_CFLAGS FT2_LIBS HAVE_FREETYPE2_TRUE HAVE_FREETYPE2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE LAME_3_89 LAME_CFLAGS LAME_LIBS HAVE_LAME_TRUE HAVE_LAME_FALSE LAME_3_89_TRUE LAME_3_89_FALSE OGG_CFLAGS OGG_LIBS HAVE_OGG_TRUE HAVE_OGG_FALSE VORBIS_CFLAGS VORBIS_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE THEORA_CFLAGS THEORA_LIBS HAVE_THEORA_TRUE HAVE_THEORA_FALSE DVDREAD_CFLAGS DVDREAD_LIBS HAVE_LIBDVDREAD_TRUE HAVE_LIBDVDREAD_FALSE XVID_DEFAULT LIBMPEG3_LIBS LIBMPEG3_CFLAGS HAVE_LIBMPEG3_TRUE HAVE_LIBMPEG3_FALSE LIBPOSTPROC_LIBS LIBPOSTPROC_CFLAGS HAVE_LIBPOSTPROC_TRUE HAVE_LIBPOSTPROC_FALSE LIBLVE_LIBS LIBLVE_CFLAGS HAVE_LIBLVE_TRUE HAVE_LIBLVE_FALSE PVM3_CFLAGS PVM3_LIB HAVE_PVM3_TRUE HAVE_PVM3_FALSE QT_LIBS QT_CFLAGS HAVE_QT_TRUE HAVE_QT_FALSE OPENQT_LIBS OPENQT_CFLAGS HAVE_OPENQT_TRUE HAVE_OPENQT_FALSE DV_LIBS DV_EXTRA_LIBS DV_CFLAGS HAVE_DV_TRUE HAVE_DV_FALSE LZO_LIBS LZO_EXTRA_LIBS LZO_CFLAGS HAVE_LZO_TRUE HAVE_LZO_FALSE A52_LIBS A52_CFLAGS HAVE_A52_TRUE HAVE_A52_FALSE USE_LIBA52_DECODER LIBXML2_CFLAGS LIBXML2_LIBS LIBXML2CONFIG HAVE_LIBXML2_TRUE HAVE_LIBXML2_FALSE MJPEG_CFLAGS MJPEG_LIBS MJPEGTOOLSCONFIG HAVE_MJPEG_TRUE HAVE_MJPEG_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries HAVE_X11_TRUE HAVE_X11_FALSE HAVE_LIBXV_TRUE HAVE_LIBXV_FALSE HAVE_XAW_SIMPLE_TRUE HAVE_XAW_SIMPLE_FALSE HAVE_LIBXPM_TRUE HAVE_LIBXPM_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE HAVE_DIVX_DECORE_TRUE HAVE_DIVX_DECORE_FALSE HAVE_DIVX_ENCORE2_TRUE HAVE_DIVX_ENCORE2_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS HAVE_GTK_TRUE HAVE_GTK_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE MAGICK_CONFIG MAGICK_CFLAGS MAGICK_LIBS HAVE_MAGICK_TRUE HAVE_MAGICK_FALSE LIBJPEG_CFLAGS LIBJPEG_LIBS HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE MOD_PATH HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE HAVE_SSE_TRUE HAVE_SSE_FALSE TRANSCODE_0_6_TRUE TRANSCODE_0_6_FALSE'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1102,6 +1102,9 @@ Optional Packages:
                           path to MPlayer builddir (optional)
   --with-liblve-builddir=PFX
                           path to lve builddir (optional)
+  --with-pvm3             Enable experimental pvm3 code
+  --with-pvm3-lib=PFX     prefix where local pvm3 libraries are installed
+  --with-pvm3-include=PFX prefix where local pvm3 includes are installed
   --with-qt               build quicktime dependent module (no)
   --with-qt-includes=PFX  prefix where local quicktime includes are installed
                           (optional)
@@ -10612,7 +10615,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 10615 "configure"' > conftest.$ac_ext
+  echo '#line 10618 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11141,7 +11144,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:11144: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:11147: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -12973,7 +12976,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12976 "configure"
+#line 12979 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13071,7 +13074,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13074 "configure"
+#line 13077 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16313,6 +16316,184 @@ if test x"$have_liblve" = "xyes"; then
 else
   HAVE_LIBLVE_TRUE='#'
   HAVE_LIBLVE_FALSE=
+fi
+
+
+
+
+
+# Check whether --with-pvm3 or --without-pvm3 was given.
+if test "${with_pvm3+set}" = set; then
+  withval="$with_pvm3"
+  case "${withval}" in
+  yes) ;;
+  no)  ;;
+  *) { { echo "$as_me:$LINENO: error: bad value ${withval} for --with-pvm3" >&5
+echo "$as_me: error: bad value ${withval} for --with-pvm3" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+else
+  with_pvm3=no
+fi;
+
+
+# Check whether --with-pvm3-lib or --without-pvm3-lib was given.
+if test "${with_pvm3_lib+set}" = set; then
+  withval="$with_pvm3_lib"
+  pvm3_lib="$withval"
+else
+  pvm3_lib="/usr/lib"
+fi;
+
+# Check whether --with-pvm3-include or --without-pvm3-include was given.
+if test "${with_pvm3_include+set}" = set; then
+  withval="$with_pvm3_include"
+  pvm3_include="$withval"
+else
+  pvm3_include="/usr/include"
+fi;
+
+	have_pvm3=no
+	PVM3_CFLAGS=""
+	PVM3_LIB=""
+	if test x$with_pvm3 = "x"yes ; then
+		if test x$pvm3_lib != "x" ; then
+			as_ac_File=`echo "ac_cv_file_$pvm3_include/pvm3.h" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $pvm3_include/pvm3.h" >&5
+echo $ECHO_N "checking for $pvm3_include/pvm3.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$pvm3_include/pvm3.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  pvm3_inc=yes
+fi
+
+			as_ac_File=`echo "ac_cv_file_$pvm3_lib/libpvm3.a" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $pvm3_lib/libpvm3.a" >&5
+echo $ECHO_N "checking for $pvm3_lib/libpvm3.a... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$pvm3_lib/libpvm3.a"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  pvm3_libs=yes
+fi
+
+			if test x$pvm3_inc != "x" ; then
+				if test x$pvm3_libs != "x" ; then
+					cat >>confdefs.h <<\_ACEOF
+#define HAVE_PVM3 1
+_ACEOF
+
+					echo "$as_me:$LINENO: checking for pvm3 version >= 3.4" >&5
+echo $ECHO_N "checking for pvm3 version >= 3.4... $ECHO_C" >&6
+					PVM3_CFLAGS="-I$pvm3_include"
+					PVM3_LIB="-L$pvm3_lib -lpvm3"
+					CFLAGS_OLD=$CFLAGS
+					CFLAGS="$CFLAGS $PVM3_CFLAGS"
+					if test "$cross_compiling" = yes; then
+  echo $ac_n "cross compiling; assumed OK... $ac_c"
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+						#include <stdio.h>
+						#include <pvm3.h>
+						int main ()
+						{
+						  if ((PVM_MAJOR_VERSION ==3)&&(PVM_MINOR_VERSION<4))
+						  {
+							printf("You need to upgrade pvm3 to version > 3.4\n");
+							return(1);
+						  }
+						  if (PVM_MAJOR_VERSION <3)
+						  {
+							printf("You need to upgrade pvm3 to version > 3.4\n");
+							return(1);
+						  }
+						  return 0;
+						}
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  :
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+no_pvm3=yes
+fi
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+					CFLAGS=$CFLAGS_OLD
+  					if test "x$no_pvm3" = x ; then
+     						echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+						have_pvm3=yes
+					else
+     						echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+						have_pvm3=no
+					fi
+				else
+					have_pvm3=no
+				fi
+			else
+				have_pvm3=no
+			fi
+		fi
+	fi
+
+
+
+
+
+if test x"$have_pvm3" = "xyes"; then
+  HAVE_PVM3_TRUE=
+  HAVE_PVM3_FALSE='#'
+else
+  HAVE_PVM3_TRUE='#'
+  HAVE_PVM3_FALSE=
 fi
 
 
@@ -20641,7 +20822,7 @@ LDFLAGS=`echo $LDFLAGS | sed -e 's/  */ /g'`
 
 
 
-                                                                                                                                                                                                                                                                                                                                                                                                                                              ac_config_files="$ac_config_files Makefile autotools/Makefile src/Makefile avilib/Makefile movlib/Makefile libioaux/Makefile libac3/Makefile libvo/Makefile libmpeg2/Makefile libmp3lame/Makefile libdvenc/Makefile bbmpeg/Makefile bbmpeg/tcmplex/Makefile ffmpeg/Makefile ffmpeg/libavcodec/Makefile ffmpeg/libavcodec/i386/Makefile ffmpeg/libavcodec/ppc/Makefile export/Makefile import/Makefile import/nuv/Makefile import/af6/Makefile import/net/Makefile import/v4l/Makefile import/lve/Makefile import/yuv/Makefile filter/Makefile filter/subtitler/Makefile filter/preview/Makefile filter/divxkey/Makefile filter/extsub/Makefile filter/resample/Makefile filter/test/Makefile filter/ivtc/Makefile filter/yuvdenoise/Makefile docs/Makefile docs/html/Makefile docs/man/Makefile contrib/Makefile tools/Makefile aclib/Makefile libsupport/Makefile libdldarwin/Makefile transcode.spec"
+                                                                                                                                                                                                                                                                                                                                                                                                                                                        ac_config_files="$ac_config_files Makefile autotools/Makefile src/Makefile avilib/Makefile movlib/Makefile libioaux/Makefile libac3/Makefile libvo/Makefile libmpeg2/Makefile libmp3lame/Makefile libdvenc/Makefile bbmpeg/Makefile bbmpeg/tcmplex/Makefile ffmpeg/Makefile ffmpeg/libavcodec/Makefile ffmpeg/libavcodec/i386/Makefile ffmpeg/libavcodec/ppc/Makefile export/Makefile import/Makefile import/nuv/Makefile import/af6/Makefile import/net/Makefile import/v4l/Makefile import/lve/Makefile import/yuv/Makefile filter/Makefile filter/subtitler/Makefile filter/preview/Makefile filter/divxkey/Makefile filter/extsub/Makefile filter/resample/Makefile filter/test/Makefile filter/ivtc/Makefile filter/yuvdenoise/Makefile pvm3/Makefile docs/Makefile docs/html/Makefile docs/man/Makefile contrib/Makefile tools/Makefile aclib/Makefile libsupport/Makefile libdldarwin/Makefile transcode.spec"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -20919,6 +21100,13 @@ if test -z "${HAVE_LIBLVE_TRUE}" && test -z "${HAVE_LIBLVE_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_LIBLVE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_LIBLVE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_PVM3_TRUE}" && test -z "${HAVE_PVM3_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_PVM3\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_PVM3\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -21553,6 +21741,7 @@ do
   "filter/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES filter/test/Makefile" ;;
   "filter/ivtc/Makefile" ) CONFIG_FILES="$CONFIG_FILES filter/ivtc/Makefile" ;;
   "filter/yuvdenoise/Makefile" ) CONFIG_FILES="$CONFIG_FILES filter/yuvdenoise/Makefile" ;;
+  "pvm3/Makefile" ) CONFIG_FILES="$CONFIG_FILES pvm3/Makefile" ;;
   "docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/Makefile" ;;
   "docs/html/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/html/Makefile" ;;
   "docs/man/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/man/Makefile" ;;
@@ -21799,6 +21988,10 @@ s,@LIBLVE_LIBS@,$LIBLVE_LIBS,;t t
 s,@LIBLVE_CFLAGS@,$LIBLVE_CFLAGS,;t t
 s,@HAVE_LIBLVE_TRUE@,$HAVE_LIBLVE_TRUE,;t t
 s,@HAVE_LIBLVE_FALSE@,$HAVE_LIBLVE_FALSE,;t t
+s,@PVM3_CFLAGS@,$PVM3_CFLAGS,;t t
+s,@PVM3_LIB@,$PVM3_LIB,;t t
+s,@HAVE_PVM3_TRUE@,$HAVE_PVM3_TRUE,;t t
+s,@HAVE_PVM3_FALSE@,$HAVE_PVM3_FALSE,;t t
 s,@QT_LIBS@,$QT_LIBS,;t t
 s,@QT_CFLAGS@,$QT_CFLAGS,;t t
 s,@HAVE_QT_TRUE@,$HAVE_QT_TRUE,;t t
@@ -22514,6 +22707,7 @@ static AV-frame buffering                        $statbuf
 support for network (sockets) streams            $net
 DVD navigation support with libdvdread           $have_dvdread
 link against local lame library (>=3.89) | ver   $lame89 | $lame_version
+experimental pvm3 support                        $have_pvm3
 *-*-*-*-*-*-* Codec *-*-*-*-*-*-*
 nasm dependent modules (bbmpeg)                  $nasm
 mjpegtools dependent modules                     $MJPEGTOOLSCONFIG
@@ -22546,6 +22740,7 @@ static AV-frame buffering                        $statbuf
 support for network (sockets) streams            $net
 DVD navigation support with libdvdread           $have_dvdread
 link against local lame library (>=3.89) | ver   $lame89 | $lame_version
+experimental pvm3 support                        $have_pvm3
 *-*-*-*-*-*-* Codec *-*-*-*-*-*-*
 nasm dependent modules (bbmpeg)                  $nasm
 mjpegtools dependent modules                     $MJPEGTOOLSCONFIG
