add checks for decore/encore header

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LN_S CCAS CCASFLAGS ASFLAGS SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE SUPPORTOBJECTS SUPPORTLIB SUPPORTINCL DLDARWINOBJECTS DLDARWINLIB DLDARWININCL DLLDFLAGS BIG_ENDIAN_TRUE BIG_ENDIAN_FALSE LIBOBJS ALLOCA GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS NASM NASMFLAGS HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_3DNOW_TRUE HAVE_ASM_3DNOW_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE ECHO RANLIB ac_ct_RANLIB LIBTOOL LTLIBOBJS STATBUFFER NET_STREAM_TRUE NET_STREAM_FALSE NET_STREAM AVIFILE_CONFIG AVIFILE_CFLAGS AVIFILE_LIBS HAVE_AVIFILE_TRUE HAVE_AVIFILE_FALSE FT2_CONFIG FT2_CFLAGS FT2_LIBS HAVE_FREETYPE2_TRUE HAVE_FREETYPE2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE LAME_3_89 LAME_CFLAGS LAME_LIBS HAVE_LAME_TRUE HAVE_LAME_FALSE LAME_3_89_TRUE LAME_3_89_FALSE OGG_CFLAGS OGG_LIBS HAVE_OGG_TRUE HAVE_OGG_FALSE VORBIS_CFLAGS VORBIS_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE DVDREAD_CFLAGS DVDREAD_LIBS HAVE_LIBDVDREAD_TRUE HAVE_LIBDVDREAD_FALSE XVIDCORE_CFLAGS XVIDCORE_LIBS HAVE_LIBXVID_TRUE HAVE_LIBXVID_FALSE LIBMPEG3_LIBS LIBMPEG3_CFLAGS HAVE_LIBMPEG3_TRUE HAVE_LIBMPEG3_FALSE LIBPOSTPROC_LIBS LIBPOSTPROC_CFLAGS HAVE_LIBPOSTPROC_TRUE HAVE_LIBPOSTPROC_FALSE LIBLVE_LIBS LIBLVE_CFLAGS HAVE_LIBLVE_TRUE HAVE_LIBLVE_FALSE QT_LIBS QT_CFLAGS HAVE_QT_TRUE HAVE_QT_FALSE OPENQT_LIBS OPENQT_CFLAGS HAVE_OPENQT_TRUE HAVE_OPENQT_FALSE DV_LIBS DV_EXTRA_LIBS DV_CFLAGS HAVE_DV_TRUE HAVE_DV_FALSE LZO_LIBS LZO_EXTRA_LIBS LZO_CFLAGS HAVE_LZO_TRUE HAVE_LZO_FALSE A52_LIBS A52_CFLAGS HAVE_A52_TRUE HAVE_A52_FALSE USE_LIBA52_DECODER LIBXML2_CFLAGS LIBXML2_LIBS LIBXML2CONFIG HAVE_LIBXML2_TRUE HAVE_LIBXML2_FALSE MJPEG_CFLAGS MJPEG_LIBS MJPEGTOOLSCONFIG HAVE_MJPEG_TRUE HAVE_MJPEG_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries HAVE_X11_TRUE HAVE_X11_FALSE HAVE_LIBXV_TRUE HAVE_LIBXV_FALSE HAVE_XAW_SIMPLE_TRUE HAVE_XAW_SIMPLE_FALSE HAVE_LIBXPM_TRUE HAVE_LIBXPM_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS HAVE_GTK_TRUE HAVE_GTK_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE MAGICK_CONFIG MAGICK_CFLAGS MAGICK_LIBS HAVE_MAGICK_TRUE HAVE_MAGICK_FALSE LIBJPEG_CFLAGS LIBJPEG_LIBS HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE MOD_PATH HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE HAVE_SSE_TRUE HAVE_SSE_FALSE TRANSCODE_0_6_TRUE TRANSCODE_0_6_FALSE'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LN_S CCAS CCASFLAGS ASFLAGS SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE SUPPORTOBJECTS SUPPORTLIB SUPPORTINCL DLDARWINOBJECTS DLDARWINLIB DLDARWININCL DLLDFLAGS BIG_ENDIAN_TRUE BIG_ENDIAN_FALSE LIBOBJS ALLOCA GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS NASM NASMFLAGS HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_3DNOW_TRUE HAVE_ASM_3DNOW_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE ECHO RANLIB ac_ct_RANLIB LIBTOOL LTLIBOBJS STATBUFFER NET_STREAM_TRUE NET_STREAM_FALSE NET_STREAM AVIFILE_CONFIG AVIFILE_CFLAGS AVIFILE_LIBS HAVE_AVIFILE_TRUE HAVE_AVIFILE_FALSE FT2_CONFIG FT2_CFLAGS FT2_LIBS HAVE_FREETYPE2_TRUE HAVE_FREETYPE2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE LAME_3_89 LAME_CFLAGS LAME_LIBS HAVE_LAME_TRUE HAVE_LAME_FALSE LAME_3_89_TRUE LAME_3_89_FALSE OGG_CFLAGS OGG_LIBS HAVE_OGG_TRUE HAVE_OGG_FALSE VORBIS_CFLAGS VORBIS_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE DVDREAD_CFLAGS DVDREAD_LIBS HAVE_LIBDVDREAD_TRUE HAVE_LIBDVDREAD_FALSE XVIDCORE_CFLAGS XVIDCORE_LIBS HAVE_LIBXVID_TRUE HAVE_LIBXVID_FALSE LIBMPEG3_LIBS LIBMPEG3_CFLAGS HAVE_LIBMPEG3_TRUE HAVE_LIBMPEG3_FALSE LIBPOSTPROC_LIBS LIBPOSTPROC_CFLAGS HAVE_LIBPOSTPROC_TRUE HAVE_LIBPOSTPROC_FALSE LIBLVE_LIBS LIBLVE_CFLAGS HAVE_LIBLVE_TRUE HAVE_LIBLVE_FALSE QT_LIBS QT_CFLAGS HAVE_QT_TRUE HAVE_QT_FALSE OPENQT_LIBS OPENQT_CFLAGS HAVE_OPENQT_TRUE HAVE_OPENQT_FALSE DV_LIBS DV_EXTRA_LIBS DV_CFLAGS HAVE_DV_TRUE HAVE_DV_FALSE LZO_LIBS LZO_EXTRA_LIBS LZO_CFLAGS HAVE_LZO_TRUE HAVE_LZO_FALSE A52_LIBS A52_CFLAGS HAVE_A52_TRUE HAVE_A52_FALSE USE_LIBA52_DECODER LIBXML2_CFLAGS LIBXML2_LIBS LIBXML2CONFIG HAVE_LIBXML2_TRUE HAVE_LIBXML2_FALSE MJPEG_CFLAGS MJPEG_LIBS MJPEGTOOLSCONFIG HAVE_MJPEG_TRUE HAVE_MJPEG_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries HAVE_X11_TRUE HAVE_X11_FALSE HAVE_LIBXV_TRUE HAVE_LIBXV_FALSE HAVE_XAW_SIMPLE_TRUE HAVE_XAW_SIMPLE_FALSE HAVE_LIBXPM_TRUE HAVE_LIBXPM_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE HAVE_DIVX_DECORE_TRUE HAVE_DIVX_DECORE_FALSE HAVE_DIVX_ENCORE2_TRUE HAVE_DIVX_ENCORE2_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS HAVE_GTK_TRUE HAVE_GTK_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE MAGICK_CONFIG MAGICK_CFLAGS MAGICK_LIBS HAVE_MAGICK_TRUE HAVE_MAGICK_FALSE LIBJPEG_CFLAGS LIBJPEG_LIBS HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE MOD_PATH HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE HAVE_SSE_TRUE HAVE_SSE_FALSE TRANSCODE_0_6_TRUE TRANSCODE_0_6_FALSE'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -19016,6 +19016,329 @@ else
 fi
 
 
+have_divx_decore=false
+
+for ac_header in decore.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ have_divx_decore=true
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DIVX_DECORE 1
+_ACEOF
+
+
+else
+  have_divx_decore=false
+fi
+
+done
+
+
+
+if test x"$have_divx_decore" = x"true" ; then
+  HAVE_DIVX_DECORE_TRUE=
+  HAVE_DIVX_DECORE_FALSE='#'
+else
+  HAVE_DIVX_DECORE_TRUE='#'
+  HAVE_DIVX_DECORE_FALSE=
+fi
+
+
+have_divx_encore2=false
+
+for ac_header in encore2.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+ have_divx_encore2=true
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_DIVX_ENCORE2 1
+_ACEOF
+
+
+else
+  have_divx_encore2=false
+fi
+
+done
+
+
+
+if test x"$have_divx_encore2" = x"true" ; then
+  HAVE_DIVX_ENCORE2_TRUE=
+  HAVE_DIVX_ENCORE2_FALSE='#'
+else
+  HAVE_DIVX_ENCORE2_TRUE='#'
+  HAVE_DIVX_ENCORE2_FALSE=
+fi
+
 
 have_gtk=no
 
@@ -20493,6 +20816,20 @@ echo "$as_me: error: conditional \"HAVE_SDL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_DIVX_DECORE_TRUE}" && test -z "${HAVE_DIVX_DECORE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_DIVX_DECORE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_DIVX_DECORE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_DIVX_ENCORE2_TRUE}" && test -z "${HAVE_DIVX_ENCORE2_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_DIVX_ENCORE2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_DIVX_ENCORE2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_GTK_TRUE}" && test -z "${HAVE_GTK_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_GTK\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -21323,6 +21660,10 @@ s,@SDL_CFLAGS@,$SDL_CFLAGS,;t t
 s,@SDL_LIBS@,$SDL_LIBS,;t t
 s,@HAVE_SDL_TRUE@,$HAVE_SDL_TRUE,;t t
 s,@HAVE_SDL_FALSE@,$HAVE_SDL_FALSE,;t t
+s,@HAVE_DIVX_DECORE_TRUE@,$HAVE_DIVX_DECORE_TRUE,;t t
+s,@HAVE_DIVX_DECORE_FALSE@,$HAVE_DIVX_DECORE_FALSE,;t t
+s,@HAVE_DIVX_ENCORE2_TRUE@,$HAVE_DIVX_ENCORE2_TRUE,;t t
+s,@HAVE_DIVX_ENCORE2_FALSE@,$HAVE_DIVX_ENCORE2_FALSE,;t t
 s,@GTK_CONFIG@,$GTK_CONFIG,;t t
 s,@GTK_CFLAGS@,$GTK_CFLAGS,;t t
 s,@GTK_LIBS@,$GTK_LIBS,;t t
