Theora configure check

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LN_S CCAS CCASFLAGS ASFLAGS SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE SUPPORTOBJECTS SUPPORTLIB SUPPORTINCL DLDARWINOBJECTS DLDARWINLIB DLDARWININCL DLLDFLAGS BIG_ENDIAN_TRUE BIG_ENDIAN_FALSE LIBOBJS ALLOCA GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS NASM NASMFLAGS HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_3DNOW_TRUE HAVE_ASM_3DNOW_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE ECHO RANLIB ac_ct_RANLIB LIBTOOL LTLIBOBJS STATBUFFER NET_STREAM_TRUE NET_STREAM_FALSE NET_STREAM AVIFILE_CONFIG AVIFILE_CFLAGS AVIFILE_LIBS HAVE_AVIFILE_TRUE HAVE_AVIFILE_FALSE FT2_CONFIG FT2_CFLAGS FT2_LIBS HAVE_FREETYPE2_TRUE HAVE_FREETYPE2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE LAME_3_89 LAME_CFLAGS LAME_LIBS HAVE_LAME_TRUE HAVE_LAME_FALSE LAME_3_89_TRUE LAME_3_89_FALSE OGG_CFLAGS OGG_LIBS HAVE_OGG_TRUE HAVE_OGG_FALSE VORBIS_CFLAGS VORBIS_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE DVDREAD_CFLAGS DVDREAD_LIBS HAVE_LIBDVDREAD_TRUE HAVE_LIBDVDREAD_FALSE XVIDCORE_CFLAGS XVIDCORE_LIBS HAVE_LIBXVID_TRUE HAVE_LIBXVID_FALSE LIBMPEG3_LIBS LIBMPEG3_CFLAGS HAVE_LIBMPEG3_TRUE HAVE_LIBMPEG3_FALSE LIBPOSTPROC_LIBS LIBPOSTPROC_CFLAGS HAVE_LIBPOSTPROC_TRUE HAVE_LIBPOSTPROC_FALSE LIBLVE_LIBS LIBLVE_CFLAGS HAVE_LIBLVE_TRUE HAVE_LIBLVE_FALSE QT_LIBS QT_CFLAGS HAVE_QT_TRUE HAVE_QT_FALSE OPENQT_LIBS OPENQT_CFLAGS HAVE_OPENQT_TRUE HAVE_OPENQT_FALSE DV_LIBS DV_EXTRA_LIBS DV_CFLAGS HAVE_DV_TRUE HAVE_DV_FALSE LZO_LIBS LZO_EXTRA_LIBS LZO_CFLAGS HAVE_LZO_TRUE HAVE_LZO_FALSE A52_LIBS A52_CFLAGS HAVE_A52_TRUE HAVE_A52_FALSE USE_LIBA52_DECODER LIBXML2_CFLAGS LIBXML2_LIBS LIBXML2CONFIG HAVE_LIBXML2_TRUE HAVE_LIBXML2_FALSE MJPEG_CFLAGS MJPEG_LIBS MJPEGTOOLSCONFIG HAVE_MJPEG_TRUE HAVE_MJPEG_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries HAVE_X11_TRUE HAVE_X11_FALSE HAVE_LIBXV_TRUE HAVE_LIBXV_FALSE HAVE_XAW_SIMPLE_TRUE HAVE_XAW_SIMPLE_FALSE HAVE_LIBXPM_TRUE HAVE_LIBXPM_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE HAVE_DIVX_DECORE_TRUE HAVE_DIVX_DECORE_FALSE HAVE_DIVX_ENCORE2_TRUE HAVE_DIVX_ENCORE2_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS HAVE_GTK_TRUE HAVE_GTK_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE MAGICK_CONFIG MAGICK_CFLAGS MAGICK_LIBS HAVE_MAGICK_TRUE HAVE_MAGICK_FALSE LIBJPEG_CFLAGS LIBJPEG_LIBS HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE MOD_PATH HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE HAVE_SSE_TRUE HAVE_SSE_FALSE TRANSCODE_0_6_TRUE TRANSCODE_0_6_FALSE'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE LN_S CCAS CCASFLAGS ASFLAGS SYSTEM_DARWIN_TRUE SYSTEM_DARWIN_FALSE SUPPORTOBJECTS SUPPORTLIB SUPPORTINCL DLDARWINOBJECTS DLDARWINLIB DLDARWININCL DLLDFLAGS BIG_ENDIAN_TRUE BIG_ENDIAN_FALSE LIBOBJS ALLOCA GLIB_CONFIG GLIB_CFLAGS GLIB_LIBS NASM NASMFLAGS HAVE_ASM_MMX_TRUE HAVE_ASM_MMX_FALSE HAVE_ASM_3DNOW_TRUE HAVE_ASM_3DNOW_FALSE HAVE_ASM_NASM_TRUE HAVE_ASM_NASM_FALSE HAVE_X86CPU_TRUE HAVE_X86CPU_FALSE ARCH_X86_TRUE ARCH_X86_FALSE ARCH_PPC_TRUE ARCH_PPC_FALSE CAN_COMPILE_C_ALTIVEC_TRUE CAN_COMPILE_C_ALTIVEC_FALSE ECHO RANLIB ac_ct_RANLIB LIBTOOL LTLIBOBJS STATBUFFER NET_STREAM_TRUE NET_STREAM_FALSE NET_STREAM AVIFILE_CONFIG AVIFILE_CFLAGS AVIFILE_LIBS HAVE_AVIFILE_TRUE HAVE_AVIFILE_FALSE FT2_CONFIG FT2_CFLAGS FT2_LIBS HAVE_FREETYPE2_TRUE HAVE_FREETYPE2_FALSE HAVE_V4L_TRUE HAVE_V4L_FALSE LAME_3_89 LAME_CFLAGS LAME_LIBS HAVE_LAME_TRUE HAVE_LAME_FALSE LAME_3_89_TRUE LAME_3_89_FALSE OGG_CFLAGS OGG_LIBS HAVE_OGG_TRUE HAVE_OGG_FALSE VORBIS_CFLAGS VORBIS_LIBS HAVE_VORBIS_TRUE HAVE_VORBIS_FALSE THEORA_CFLAGS THEORA_LIBS HAVE_THEORA_TRUE HAVE_THEORA_FALSE DVDREAD_CFLAGS DVDREAD_LIBS HAVE_LIBDVDREAD_TRUE HAVE_LIBDVDREAD_FALSE XVIDCORE_CFLAGS XVIDCORE_LIBS HAVE_LIBXVID_TRUE HAVE_LIBXVID_FALSE LIBMPEG3_LIBS LIBMPEG3_CFLAGS HAVE_LIBMPEG3_TRUE HAVE_LIBMPEG3_FALSE LIBPOSTPROC_LIBS LIBPOSTPROC_CFLAGS HAVE_LIBPOSTPROC_TRUE HAVE_LIBPOSTPROC_FALSE LIBLVE_LIBS LIBLVE_CFLAGS HAVE_LIBLVE_TRUE HAVE_LIBLVE_FALSE QT_LIBS QT_CFLAGS HAVE_QT_TRUE HAVE_QT_FALSE OPENQT_LIBS OPENQT_CFLAGS HAVE_OPENQT_TRUE HAVE_OPENQT_FALSE DV_LIBS DV_EXTRA_LIBS DV_CFLAGS HAVE_DV_TRUE HAVE_DV_FALSE LZO_LIBS LZO_EXTRA_LIBS LZO_CFLAGS HAVE_LZO_TRUE HAVE_LZO_FALSE A52_LIBS A52_CFLAGS HAVE_A52_TRUE HAVE_A52_FALSE USE_LIBA52_DECODER LIBXML2_CFLAGS LIBXML2_LIBS LIBXML2CONFIG HAVE_LIBXML2_TRUE HAVE_LIBXML2_FALSE MJPEG_CFLAGS MJPEG_LIBS MJPEGTOOLSCONFIG HAVE_MJPEG_TRUE HAVE_MJPEG_FALSE X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS x_includes x_libraries HAVE_X11_TRUE HAVE_X11_FALSE HAVE_LIBXV_TRUE HAVE_LIBXV_FALSE HAVE_XAW_SIMPLE_TRUE HAVE_XAW_SIMPLE_FALSE HAVE_LIBXPM_TRUE HAVE_LIBXPM_FALSE SDL_CONFIG SDL_CFLAGS SDL_LIBS HAVE_SDL_TRUE HAVE_SDL_FALSE HAVE_DIVX_DECORE_TRUE HAVE_DIVX_DECORE_FALSE HAVE_DIVX_ENCORE2_TRUE HAVE_DIVX_ENCORE2_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS HAVE_GTK_TRUE HAVE_GTK_FALSE LIBFAME_CONFIG LIBFAME_CFLAGS LIBFAME_LIBS HAVE_LIBFAME_TRUE HAVE_LIBFAME_FALSE MAGICK_CONFIG MAGICK_CFLAGS MAGICK_LIBS HAVE_MAGICK_TRUE HAVE_MAGICK_FALSE LIBJPEG_CFLAGS LIBJPEG_LIBS HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE MOD_PATH HAVE_PPC_ALTIVEC_TRUE HAVE_PPC_ALTIVEC_FALSE HAVE_MMX_TRUE HAVE_MMX_FALSE HAVE_SSE_TRUE HAVE_SSE_FALSE TRANSCODE_0_6_TRUE TRANSCODE_0_6_FALSE'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1076,6 +1076,12 @@ Optional Packages:
                           prefix where local vorbis includes are installed
                           (optional)
   --with-vorbis-libs=PFX  prefix where local vorbis libs are installed
+                          (optional)
+  --with-theora           Compile in libtheora support
+  --with-theora-includes=PFX
+                          prefix where local theora includes are installed
+                          (optional)
+  --with-theora-libs=PFX  prefix where local theora libs are installed
                           (optional)
   --with-dvdread          use installed libdvdread library (yes)
   --with-dvdread-includes=PFX
@@ -10610,7 +10616,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 10613 "configure"' > conftest.$ac_ext
+  echo '#line 10619 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -11139,7 +11145,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:11142: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:11148: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -12971,7 +12977,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12974 "configure"
+#line 12980 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13069,7 +13075,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 13072 "configure"
+#line 13078 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -15272,6 +15278,184 @@ else
   HAVE_VORBIS_FALSE=
 fi
 
+
+
+
+# Check whether --with-theora or --without-theora was given.
+if test "${with_theora+set}" = set; then
+  withval="$with_theora"
+  case "${withval}" in
+  yes) ;;
+  no)  ;;
+  *) { { echo "$as_me:$LINENO: error: bad value ${withval} for --with-theora" >&5
+echo "$as_me: error: bad value ${withval} for --with-theora" >&2;}
+   { (exit 1); exit 1; }; } ;;
+esac
+else
+  with_theora=yes
+fi;
+
+
+# Check whether --with-theora-includes or --without-theora-includes was given.
+if test "${with_theora_includes+set}" = set; then
+  withval="$with_theora_includes"
+  theora_includes="$withval"
+else
+  theora_includes=""
+fi;
+
+
+# Check whether --with-theora-libs or --without-theora-libs was given.
+if test "${with_theora_libs+set}" = set; then
+  withval="$with_theora_libs"
+  theora_libs="$withval"
+else
+  theora_libs=""
+fi;
+
+THEORA_LIBS=""
+THEORA_CFLAGS=""
+
+have_theora=no
+
+if test x$with_theora = "x"yes ; then
+	if test x$theora_includes != "x" ; then
+	    with_theora_i="$theora_includes/include"
+        else
+	    with_theora_i="/usr/include"
+        fi
+
+        if test x$theora_libs != x ; then
+	    with_theora_l="$theora_libs/lib"
+        else
+	    with_theora_l="/usr/lib"
+        fi
+
+	echo "$as_me:$LINENO: checking for theora_version_number in -ltheora" >&5
+echo $ECHO_N "checking for theora_version_number in -ltheora... $ECHO_C" >&6
+if test "${ac_cv_lib_theora_theora_version_number+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-ltheora -L$with_theora_l -ltheora $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char theora_version_number ();
+int
+main ()
+{
+theora_version_number ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_theora_theora_version_number=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_theora_theora_version_number=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_theora_theora_version_number" >&5
+echo "${ECHO_T}$ac_cv_lib_theora_theora_version_number" >&6
+if test $ac_cv_lib_theora_theora_version_number = yes; then
+  THEORA_CFLAGS="-I$with_theora_i -I/usr/local/include"
+         THEORA_LIBS="-L$with_theora_l -ltheora -lm"
+       	cat >>confdefs.h <<\_ACEOF
+#define HAVE_THEORA 1
+_ACEOF
+
+	hav_theora=yes
+	have_theora=yes
+else
+  have_theora=no
+fi
+
+fi
+as_ac_File=`echo "ac_cv_file_$with_theora_i/theora/codec.h" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $with_theora_i/theora/codec.h" >&5
+echo $ECHO_N "checking for $with_theora_i/theora/codec.h... $ECHO_C" >&6
+if eval "test \"\${$as_ac_File+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "$with_theora_i/theora/codec.h"; then
+  eval "$as_ac_File=yes"
+else
+  eval "$as_ac_File=no"
+fi
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_File'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_File'}'`" >&6
+if test `eval echo '${'$as_ac_File'}'` = yes; then
+  theora_inc=yes
+fi
+
+if test x"$theora_inc" != xyes; then
+echo "$as_me:$LINENO: checking for /usr/local/include/theora/codec.h" >&5
+echo $ECHO_N "checking for /usr/local/include/theora/codec.h... $ECHO_C" >&6
+if test "${ac_cv_file__usr_local_include_theora_codec_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "/usr/local/include/theora/codec.h"; then
+  ac_cv_file__usr_local_include_theora_codec_h=yes
+else
+  ac_cv_file__usr_local_include_theora_codec_h=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file__usr_local_include_theora_codec_h" >&5
+echo "${ECHO_T}$ac_cv_file__usr_local_include_theora_codec_h" >&6
+if test $ac_cv_file__usr_local_include_theora_codec_h = yes; then
+  theora_inc=yes
+fi
+
+fi
+
+
+
+
+
+if test x"$have_theora" = "xyes"; then
+  HAVE_THEORA_TRUE=
+  HAVE_THEORA_FALSE='#'
+else
+  HAVE_THEORA_TRUE='#'
+  HAVE_THEORA_FALSE=
+fi
 
 
 
@@ -20813,6 +20997,13 @@ echo "$as_me: error: conditional \"HAVE_VORBIS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${HAVE_THEORA_TRUE}" && test -z "${HAVE_THEORA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_THEORA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_THEORA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${HAVE_LIBDVDREAD_TRUE}" && test -z "${HAVE_LIBDVDREAD_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_LIBDVDREAD\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -21704,6 +21895,10 @@ s,@VORBIS_CFLAGS@,$VORBIS_CFLAGS,;t t
 s,@VORBIS_LIBS@,$VORBIS_LIBS,;t t
 s,@HAVE_VORBIS_TRUE@,$HAVE_VORBIS_TRUE,;t t
 s,@HAVE_VORBIS_FALSE@,$HAVE_VORBIS_FALSE,;t t
+s,@THEORA_CFLAGS@,$THEORA_CFLAGS,;t t
+s,@THEORA_LIBS@,$THEORA_LIBS,;t t
+s,@HAVE_THEORA_TRUE@,$HAVE_THEORA_TRUE,;t t
+s,@HAVE_THEORA_FALSE@,$HAVE_THEORA_FALSE,;t t
 s,@DVDREAD_CFLAGS@,$DVDREAD_CFLAGS,;t t
 s,@DVDREAD_LIBS@,$DVDREAD_LIBS,;t t
 s,@HAVE_LIBDVDREAD_TRUE@,$HAVE_LIBDVDREAD_TRUE,;t t
@@ -22443,7 +22638,7 @@ link against local lame library (>=3.89) | ver   $lame89 | $lame_version
 nasm dependent modules (bbmpeg)                  $nasm
 mjpegtools dependent modules                     $MJPEGTOOLSCONFIG
 libdv dependent modules			         $have_dv
-Ogg support | Vorbis support                     $have_ogg | $have_vorbis
+Ogg support | Vorbis support | Theora support    $have_ogg | $have_vorbis | $have_theora
 XVID support with libxvidcore                    $have_xvidcore
 liba52 audio plugin (>=0.7.3) | default decoder  $have_a52 | $a52_decoder
 avifile API support                              $have_avifile
@@ -22475,7 +22670,7 @@ link against local lame library (>=3.89) | ver   $lame89 | $lame_version
 nasm dependent modules (bbmpeg)                  $nasm
 mjpegtools dependent modules                     $MJPEGTOOLSCONFIG
 libdv dependent modules			         $have_dv
-Ogg support | Vorbis support                     $have_ogg | $have_vorbis
+Ogg support | Vorbis support | Theora support    $have_ogg | $have_vorbis | $have_theora
 XVID support with libxvidcore                    $have_xvidcore
 liba52 audio plugin (>=0.7.3) | default decoder  $have_a52 | $a52_decoder
 avifile API support                              $have_avifile
