detect linux/videodev2.h

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24344,6 +24344,7 @@ fi
 
 
 
+
 echo "$as_me:$LINENO: checking for v4l support" >&5
 echo $ECHO_N "checking for v4l support... $ECHO_C" >&6
 # Check whether --enable-v4l or --disable-v4l was given.
@@ -24378,6 +24379,145 @@ else
   HAVE_V4L_TRUE='#'
   HAVE_V4L_FALSE=
 fi
+
+
+if test "${ac_cv_header_linux_videodev2_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for linux/videodev2.h" >&5
+echo $ECHO_N "checking for linux/videodev2.h... $ECHO_C" >&6
+if test "${ac_cv_header_linux_videodev2_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_linux_videodev2_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_videodev2_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking linux/videodev2.h usability" >&5
+echo $ECHO_N "checking linux/videodev2.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <linux/videodev2.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking linux/videodev2.h presence" >&5
+echo $ECHO_N "checking linux/videodev2.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <linux/videodev2.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: linux/videodev2.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: linux/videodev2.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/videodev2.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: linux/videodev2.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: linux/videodev2.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: linux/videodev2.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/videodev2.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: linux/videodev2.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: linux/videodev2.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: linux/videodev2.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for linux/videodev2.h" >&5
+echo $ECHO_N "checking for linux/videodev2.h... $ECHO_C" >&6
+if test "${ac_cv_header_linux_videodev2_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_linux_videodev2_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_linux_videodev2_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_videodev2_h" >&6
+
+fi
+if test $ac_cv_header_linux_videodev2_h = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LINUX_VIDEODEV2_H 1
+_ACEOF
+
+fi
+
 
 
 
